const assert=require('node:assert/strict');
const T=require('../static/surface-tools.js');
const data=[{type:'surface',x:[1,10,100],y:[1,2],z:[[1,2,3],[2,3,4]]},{type:'scatter3d',x:[1],y:[2],z:[3]}];
const layout={scene:{xaxis:{title:{text:'θ'},range:[-10,10]},yaxis:{title:{text:'φ'}},zaxis:{title:{text:'f'}}}};
const original=JSON.stringify({data,layout});
let o=T.settings(null);
o.axes.x={title:'Position <x>',type:'log',range:[1,100]};o.axes.z.range=[0,5];o.aspect='manual';o.zRatio=2;o.background=false;o.contours=true;o.floor=true;o.colorRange=[1,4];o.camera=T.preset('top');o.projection='orthographic';
let p=T.apply(data,layout,o);
assert.deepEqual(p.layout.scene.xaxis.range,[0,2]);
assert.equal(p.layout.scene.xaxis.title.text,'Position &lt;x&gt;');
assert.equal(p.layout.scene.yaxis.title.text,'φ');
assert.equal(p.layout.scene.yaxis.autorange,true);
assert.equal(p.layout.scene.zaxis.showbackground,false);
assert.equal(p.layout.scene.camera.projection.type,'orthographic');
assert.deepEqual(p.layout.scene.aspectratio,{x:1,y:1,z:2});
assert.equal(p.data[0].contours.z.project.z,true);
assert.equal(p.data[0].cmin,1);assert.equal(p.data[0].cmax,4);assert.equal(p.data[0].cauto,false);
assert.equal(p.data[1],data[1]);
assert.equal(JSON.stringify({data,layout}),original,'Never mutate cached sampled data');
assert.deepEqual(T.settings(JSON.parse(JSON.stringify(o))),o,'Worksheet roundtrip');
assert.throws(()=>T.settings({axes:{x:{range:[2,1]}}}),/minimum/);
assert.throws(()=>T.settings({axes:{z:{type:'log',range:[0,1]}}}),/positive/);
assert.throws(()=>T.apply([{type:'surface',x:[0,1],y:[1],z:[[2,3]]}],layout,o),/positive plotted values/);
assert.throws(()=>T.settings({opacity:NaN}));assert.throws(()=>T.settings({colorscale:'<bad>'}));
assert.throws(()=>T.settings({camera:{eye:{x:0,y:0,z:0}}}));
assert.throws(()=>T.settings({axes:{x:{title:'a'.repeat(81)}}}));
const phase=T.apply([{...data[0],colorscale:'HSV',cmin:-Math.PI,cmax:Math.PI}],layout,null);
assert.equal(phase.data[0].colorscale,'HSV');assert.equal(phase.data[0].cmin,-Math.PI);
assert.equal(phase.layout.scene.xaxis.range,undefined,'Sampling bounds are not display limits');
assert.deepEqual(T.apply([],layout,null),{data:[],layout});
console.log('Surface tools: axes, log ranges, camera, theme flags, contours, color limits, safe labels, persistence, and cached-data isolation passed.');

const multiple=T.apply([data[0],{...data[0],z:[[10,20],[30,40]]}],layout,null);
assert.equal(multiple.data[0].cmin,1);assert.equal(multiple.data[0].cmax,40);
assert.equal(multiple.data[1].cmax,40);assert.equal(multiple.data[1].showscale,false);
