'use strict';
const assert=require('node:assert/strict'),g=require('../static/graph-tools.js');
let spec=g.fresh('vectorfield','f');
let result={id:'f',positions:[[0,0],[1,0],[2,0]],vectors:[[1,0],[0,2],[0,0]],magnitudes:[1,2,0],spacing:1};
let plot=g.plot([spec],[result],'2d');
assert.equal(plot.data.length,2);assert.equal(plot.data[0].type,'scatter');
assert.deepEqual(plot.data[0].x.slice(0,3),[0,.4,null]);
assert.deepEqual(plot.data[1].customdata,[[1,0,1],[0,2,2],[0,0,0]]);
assert.equal(plot.layout.yaxis.scaleanchor,'x');
spec.normalize=true;plot=g.plot([spec],[result],'2d');assert.equal(plot.data[0].x[1],.8);
const three=g.fresh('vectorfield3d','space');
result={id:'space',positions:[[0,0,0]],vectors:[[0,0,1]],magnitudes:[1],spacing:1};
plot=g.plot([three],[result],'3d');assert.equal(plot.data[0].type,'scatter3d');assert.deepEqual(plot.data[0].z.slice(0,3),[0,.8,null]);
assert.equal(g.plot([three],[result],'2d').data.length,0);
assert.deepEqual(g.validate(JSON.parse(JSON.stringify([three]))),[three]);
for(const changes of [{density:12},{normalize:'yes'},{arrow_scale:3},{zrange:[1,0]}])assert.throws(()=>g.validate([{...three,...changes}]));
const zero={...result,vectors:[[0,0,0]],magnitudes:[0]};assert.equal(g.plot([three],[zero],'3d').data[0].x.length,0);assert.equal(g.plot([three],[zero],'3d').data[1].x.length,1);
const catalog=require('../static/function-catalog.js');
for(const label of ['Field curl','Field divergence','Force −∇U','Work integral','Field Jacobian'])assert(catalog.entries.some(e=>e.label===label));
console.log('Vector fields: arrow direction and scaling, zero vectors, actual magnitudes, 2D/3D separation, controls and worksheet roundtrip passed.');
