'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const SurfaceTools=require('../static/surface-tools.js');
const elements={};
function $(id){return elements[id]??=(Object.assign({value:'',type:'text',checked:false,hidden:false,disabled:false,textContent:'',title:'',showModal(){this.open=true;},close(){this.open=false;}},id==='plot'?{data:[{type:'surface',x:[1,2],y:[1,2],z:[[1,2],[3,4]]}],layout:{scene:{}}}:{}));}
for(const n of ['grid','background','reverse','colorbar','contours','floor'])$('surfaceDisplay_'+n).type='checkbox';
for(const n of ['zRatio','opacity'])$('surfaceDisplay_'+n).type='number';
let draws=0,saves=0,fetches=[];
const context={SurfaceTools,$,surfaceSettings:SurfaceTools.settings(null),window:{},view:'surface',saveLocal(){saves++;},drawPlot(){draws++;},toast(){},fetch:async url=>{fetches.push(url);return {ok:true,json:async()=>({mode:'celery',workers:8,nodes:2})};}};
vm.createContext(context);vm.runInContext(fs.readFileSync('static/surface-controls.js','utf8'),context);
$('surfaceControlsBtn').onclick();assert.equal($('surfaceDisplayDialog').open,true);
$('surfaceDisplay_xTitle').value='Time';$('surfaceDisplay_xMin').value='1';$('surfaceDisplay_xMax').value='10';$('surfaceDisplay_camera').value='top';
$('surfaceDisplayForm').onsubmit({preventDefault(){}});
assert.equal(context.surfaceSettings.axes.x.title,'Time');assert.equal(draws,1);assert.equal(saves,1);
assert.equal($('surfaceDisplayDialog').open,false);
assert.deepEqual(JSON.parse(JSON.stringify(context.surfaceSettings.camera)),SurfaceTools.preset('top'));
$('surfaceControlsBtn').onclick();$('surfaceDisplay_xMin').value='1';$('surfaceDisplay_xMax').value='0';
$('surfaceDisplayForm').onsubmit({preventDefault(){}});
assert.match($('surfaceDisplayError').textContent,/minimum/);assert.equal(draws,1);assert.equal($('surfaceDisplayDialog').open,true);
context.window.SurfaceControls.capture({'scene.camera':SurfaceTools.preset('side')});
assert.deepEqual(JSON.parse(JSON.stringify(context.surfaceSettings.camera)),SurfaceTools.preset('side'));
const prior=context.surfaceSettings.camera;context.view='quantum';context.window.SurfaceControls.capture({'scene.camera':SurfaceTools.preset('front')});assert.equal(context.surfaceSettings.camera,prior);
context.view='surface';context.window.SurfaceControls.reset();assert.equal(draws,2);assert.equal(context.surfaceSettings.axes.x.title,'Time');
$('surfaceDisplayDefaults').onclick();assert.equal(context.surfaceSettings.axes.x.range,null);assert.equal(draws,3);
assert.deepEqual(fetches,['/api/compute/status'],'Display changes must never submit calculation jobs');
const app=fs.readFileSync('static/app.js','utf8');
assert.match(app,/surface_settings:surfaceSettings/);assert.match(app,/SurfaceTools.settings\(data.surface_settings\)/);
assert.match(app,/showbackground:layout.scene\[name\].showbackground\?\?true/);
const html=fs.readFileSync('templates/index.html','utf8');
assert.ok(html.indexOf("filename='surface-tools.js'")<html.indexOf("filename='app.js'"));
assert.ok(html.indexOf("filename='surface-controls.js'")>html.indexOf("filename='app.js'"));
for(const id of Object.keys(elements))assert.ok(html.includes(`id="${id}"`),id+' is present');
console.log('Surface controls: apply, validation, save, camera capture/reset, quantum isolation, and display changes without computation passed.');
